SELECT * FROM MOVIE WHERE M_Name='타이타닉';
SELECT M_NAME FROM MOVIE WHERE M_Name LIKE '%타%';
SELECT M_ID, COUNT(M_ID) FROM RECORD GROUP BY M_ID;

-- 인덱스 만들기 --
CREATE INDEX INDEX_MOVIE_NAME ON MOVIE(M_Name);
CREATE INDEX INDEX_MOVIE_DIRECTOR ON MOVIE(M_Director);

-- 인덱스 보기 --
show index from MOVIE;
show index from BELONG;

-- 인덱스 지우기 --
ALTER TABLE MOVIE DROP INDEX INDEX_MOVIE_NAME;
ALTER TABLE MOVIE DROP INDEX INDEX_MOVIE_DIRECTOR;